### ISSUE TITLE
Tries to build non-sass projects

### ISSUE THREAD

**Issue by Qard** [idleberg/atom-build-sass#1]
This plugin appears to be running when it shouldn't. I've been working on projects with no sass in them anywhere, but this keeps trying to run anyway. It seems atom-build has no way to select no target, so if any build providers claim to support a project when they actually don't it'll still run it anyway and there's no way to stop it. Every time I save a file I get a big ugly build failure panel popping up. 😿

**Comment by idleberg** [comment]
You will have to select the build provider you want to use in the lower left corner of the Atom window:

![screen shot 2016-11-12 at 01 21 59](https://cloud.githubusercontent.com/assets/1504938/20234023/71e8e46e-a876-11e6-9c81-e38755938f38.png)

The build provider is eligible once `sass` is present on your system. If I understand you correctly, you are looking for automatic provider selection (like in Sublime Text), so whenever you switch to another file type, the appropriate provider is chosen? I haven't seen any other build provider doing this.

As a workaround, you could map different keyboard shortcuts to different build commands.

**Comment by Qard** [comment]
No, I want sass to _not_ be eligible if there's no sass files in the project.

Currently every project on my system is recognized as a sass project, even when it's not, simply because I have sass installed. With atom-build, you can't select "no target" or anything like that from the build selector in the corner. It assumes that if something claims to be "eligible" that it is capable of building the project. In this case, it's not. It fails because it can't find any sass files to build when it tries to run the build job.

**Comment by idleberg** [comment]
I'd actually like to go a step further and only show providers eligible for the active file. This, however, adds some complications that –IMHO– should be addressed in the build package rather than in its providers. For instance, when there are multiple eligible targets, you would lose the preferred target when jumping back and forth between panes that use different grammar.

**Comment by Qard** [comment]
That'd involve a breaking change from how isEligible currently works, and would make the more typical project-based build formats a lot more complicated.

For example, if you have a Makefile and are editing something else in the project which that Makefile influences, you'd want to trigger the build task for the Makefile, but then the isEligible check for the Makefile build plugin would need to be aware of every possible file type that can influence that build.

**Comment by idleberg** [comment]
I don't want to break `isEligible()`, what I was suggesting is some way for build to _remember_ the last used target for each file type. For this particular provider, I'd still prefer the eligibility test to run for the active editor only (I have currently 20+ providers installed, imagine the fun!), but it's not applicable when build doesn't remember previous targets. Also, don't you think scanning the entire project folder would be slow?

Anyway, I have tried implementing a better test in the past. Basically, it emits `this.refresh()` when the active pane is changed. The main problem is selecting a non-editor panel, since it breaks the refresh event.

``` js
isEligible() {
  let editor = atom.workspace.getActiveTextEditor();

  if (typeof editor === 'undefined') {
    return false;
  }

  // additional scope test
  return true;
}
```

Let me post the exact code when I get home, maybe you have any ideas how to improve it.

**Comment by idleberg** [comment]
> With atom-build, you can't select "no target" or anything like that

Why do you trigger a build when you don't want to build anything?

**Comment by Qard** [comment]
atom-build runs it automatically when I save a file.

As for file-based vs project-based, atom-build is somewhat more intended for project-based build systems. Building individual files is more something a file watcher should handle, and that often requires some separate per-project configuration like specifying the output directory or other such things you'd typically do with a custom build system like gulp.

I think I might just remove this plugin and stick to a file watcher.

**Comment by idleberg** [comment]
Regardless of your decision, please keep the issue open.

**Comment by idleberg** [comment]
I've added an optional project eligibility test in `v0.6.0`. It's far from ideal, it's synchronous and I didn't manage to find a glob package that supports multiple patterns _and_ allows the exclusion of folders (though `globby` claims to support that!) Well, I'm not a Node developer, this is the best I can do.

If this proves to work, I will adopt it for my other providers.
